import React, { createContext, useContext, useState } from 'react';

type Language = 'vi' | 'en';

// Simple dictionary translation structure
const translations = {
  vi: {
    "login.title": "Đăng Nhập",
    "login.email": "Địa chỉ Email",
    "login.password": "Mật khẩu",
    "login.submit": "Đăng Nhập",
    "login.forgot": "Quên mật khẩu?",
    "login.registerLink": "Chưa có tài khoản? Đăng ký ngay",
    "login.google": "Đăng nhập bằng Google",
    "register.title": "Đăng Ký Tài Khoản",
    "register.firstName": "Tên",
    "register.lastName": "Họ",
    "register.submit": "Đăng Ký",
    "register.loginLink": "Đã có tài khoản? Đăng nhập",
    "forgot.title": "Khôi Phục Mật Khẩu",
    "forgot.submit": "Gửi liên kết khôi phục",
    "forgot.back": "Quay lại Đăng nhập",
    "logout": "Đăng xuất",
    "dashboard": "Bảng điều khiển",
    "student": "Sinh viên",
    "admin": "Quản trị viên",
    "common.required": "Trường này là bắt buộc.",
    "profile.title": "Hồ Sơ Cá Nhân",
    "profile.subtitle": "Quản lý thông tin học tập, tài khoản và tùy chọn giao diện của bạn",
    "profile.academicInfo": "Thông Tin Học Tập",
    "profile.personalInfo": "Thông Tin Cá Nhân",
    "profile.preferences": "Cài Đặt Hiển Thị",
    "profile.changePassword": "Đổi Mật Khẩu",
    "profile.studentCode": "Mã số sinh viên",
    "profile.university": "Trường đại học",
    "profile.major": "Chuyên ngành",
    "profile.enrollmentYear": "Năm nhập học",
    "profile.requiredCredits": "Số tín chỉ yêu cầu",
    "profile.firstName": "Tên",
    "profile.lastName": "Họ",
    "profile.email": "Địa chỉ Email",
    "profile.save": "Lưu Thay Đổi",
    "profile.avatarUpload": "Đổi ảnh đại diện",
    "profile.currentPassword": "Mật khẩu hiện tại",
    "profile.newPassword": "Mật khẩu mới",
    "profile.confirmPassword": "Xác nhận mật khẩu mới",
    "profile.passwordMismatch": "Mật khẩu xác nhận không trùng khớp.",
    "profile.success": "Cập nhật thành công!",
    "theme.light": "Sáng",
    "theme.dark": "Tối",
    "lang.vi": "Tiếng Việt",
    "lang.en": "Tiếng Anh",
    "nav.academicYears": "Năm Học",
    "nav.statistics": "Thống Kê",
    "nav.goalPlanner": "Kế Hoạch Mục Tiêu",
    "nav.aiAdvisor": "Cố Vấn Học Tập AI",
    "aiAdvisor.errLoadInsights": "Không thể tải báo cáo phân tích học tập.",
    "aiAdvisor.errLoadMessages": "Không thể tải lịch sử trò chuyện.",
    "aiAdvisor.threadLimitExceeded": "Bạn đã đạt giới hạn tối đa 50 cuộc trò chuyện.",
    "aiAdvisor.errStartThread": "Không thể tạo cuộc hội thoại mới.",
    "aiAdvisor.deleteConfirm": "Bạn có chắc chắn muốn xóa cuộc trò chuyện này?",
    "aiAdvisor.errDeleteThread": "Không thể xóa cuộc trò chuyện.",
    "aiAdvisor.errSendMessage": "Không thể gửi tin nhắn.",
    "aiAdvisor.noConversations": "Không có lịch sử hội thoại.",
    "aiAdvisor.startChat": "Bắt đầu tư vấn",
    "academicyears.title": "Quản Lý Năm Học",
    "academicyears.subtitle": "Thêm, sửa, hoặc đánh dấu năm học hiện tại của bạn",
    "academicyears.yearName": "Tên năm học",
    "academicyears.startYear": "Năm bắt đầu",
    "academicyears.endYear": "Năm kết thúc",
    "academicyears.status": "Trạng thái",
    "academicyears.current": "Hiện tại",
    "academicyears.completed": "Đã hoàn thành",
    "academicyears.actions": "Thao tác",
    "academicyears.addNew": "Thêm Năm Học",
    "academicyears.edit": "Sửa Năm Học",
    "academicyears.delete": "Xóa",
    "academicyears.deleteConfirm": "Bạn có chắc chắn muốn xóa năm học này? Tất cả dữ liệu học tập liên quan cũng sẽ bị xóa.",
    "academicyears.save": "Lưu",
    "academicyears.cancel": "Hủy",
    "academicyears.makeCurrent": "Đặt làm hiện tại",
    "academicyears.success.create": "Thêm năm học thành công!",
    "academicyears.success.update": "Cập nhật năm học thành công!",
    "academicyears.success.setCurrent": "Đặt năm học hiện tại thành công!",
    "semesters.title": "Quản Lý Học Kỳ",
    "semesters.subtitle": "Quản lý các học kỳ trong năm học",
    "semesters.semesterName": "Tên học kỳ",
    "semesters.addNew": "Thêm Học Kỳ",
    "semesters.edit": "Sửa Học Kỳ",
    "semesters.delete": "Xóa",
    "semesters.deleteConfirm": "Bạn có chắc chắn muốn xóa học kỳ này? Tất cả dữ liệu học tập liên quan cũng sẽ bị xóa.",
    "semesters.save": "Lưu",
    "semesters.cancel": "Hủy",
    "semesters.empty": "Chưa có học kỳ nào",
    "semesters.backToYears": "Quay lại Năm học",
    "semesters.success.create": "Thêm học kỳ thành công!",
    "semesters.success.update": "Cập nhật học kỳ thành công!",
    "semesters.success.delete": "Xóa học kỳ thành công!",
    "courses.title": "Quản Lý Học Phần",
    "courses.subtitle": "Quản lý các môn học, tín chỉ và thông tin học tập của bạn",
    "courses.courseCode": "Mã học phần",
    "courses.courseName": "Tên học phần",
    "courses.credits": "Số tín chỉ",
    "courses.isRetake": "Học phần học lại",
    "courses.originalCourse": "Học phần gốc (Lần học trước)",
    "courses.status": "Trạng thái",
    "courses.status.inProgress": "Đang học",
    "courses.status.completed": "Đã hoàn thành",
    "courses.addNew": "Thêm Học Phần",
    "courses.edit": "Sửa Học Phần",
    "courses.delete": "Xóa",
    "courses.deleteConfirm": "Bạn có chắc chắn muốn xóa học phần này?",
    "courses.save": "Lưu",
    "courses.cancel": "Hủy",
    "courses.empty": "Chưa có học phần nào",
    "courses.backToSemesters": "Quay lại Học kỳ",
    "courses.searchPlaceholder": "Tìm kiếm theo tên hoặc mã học phần...",
    "courses.totalCredits": "Tổng số tín chỉ",
    "courses.success.create": "Thêm học phần thành công!",
    "courses.success.update": "Cập nhật học phần thành công!",
    "courses.success.delete": "Xóa học phần thành công!",
    "scores.title": "Quản Lý Điểm Số",
    "scores.attendance": "Điểm chuyên cần",
    "scores.continuous": "Điểm đánh giá thường xuyên",
    "scores.final": "Điểm thi kết thúc học phần",
    "scores.courseScore": "Điểm tổng kết",
    "scores.letterGrade": "Điểm chữ",
    "scores.gpa4": "Điểm hệ 4",
    "scores.classification": "Xếp loại học lực",
    "scores.status": "Kết quả",
    "scores.pass": "Đạt",
    "scores.fail": "Không đạt",
    "scores.editTitle": "Nhập điểm học phần",
    "scores.save": "Lưu điểm",
    "scores.auditLogs": "Lịch sử thay đổi",
    "scores.field": "Thành phần",
    "scores.oldVal": "Điểm cũ",
    "scores.newVal": "Điểm mới",
    "scores.changedAt": "Thời gian thay đổi",
    "scores.success.update": "Cập nhật điểm số thành công!",
    "scores.clear": "Xóa điểm",
    "scores.clearConfirm": "Bạn có chắc chắn muốn xóa điểm số của học phần này? Tất cả điểm thành phần sẽ được xóa.",
    "gpa.title": "Kết Quả Học Tập & GPA",
    "gpa.subtitle": "Theo dõi và phân tích tiến độ tích lũy, điểm trung bình GPA và xếp loại học lực của bạn",
    "gpa.cumulative": "Điểm tích lũy chung",
    "gpa.semester": "GPA Học Kỳ",
    "gpa.year": "GPA Năm Học",
    "gpa.credits.completed": "Số tín chỉ tích lũy",
    "gpa.credits.required": "Yêu cầu tích lũy",
    "gpa.progress": "Tiến độ hoàn thành",
    "gpa.classification": "Xếp loại học lực",
    "gpa.academicClassification": "Xếp loại",
    "gpa.passedCredits": "Tín chỉ đạt",
    "gpa.failedCredits": "Tín chỉ không đạt",
    "gpa.credits": "Tín chỉ",
    "gpa.average10": "Điểm trung bình (Hệ 10)",
    "gpa.average4": "Điểm trung bình (Hệ 4)",
    "gpa.semesterSelect": "Chọn học kỳ để xem chi tiết",
    "gpa.yearSelect": "Chọn năm học",
    "gpa.empty": "Chưa có kết quả học tập nào được ghi nhận. Vui lòng nhập điểm môn học để tính toán GPA.",
    "nav.settings": "Cài đặt",
    "settings.title": "Cài Đặt Hệ Thống",
    "settings.subtitle": "Quản lý tùy chọn hiển thị, thông báo và bảo mật tài khoản",
    "settings.preferences": "Cài đặt hiển thị",
    "settings.notifications": "Cài đặt thông báo",
    "settings.account": "Cài đặt tài khoản",
    "settings.email": "Địa chỉ Email",
    "settings.changeEmail": "Cập nhật Email",
    "settings.changePassword": "Đổi mật khẩu",
    "settings.save": "Lưu thay đổi",
    "settings.success": "Cập nhật cài đặt thành công!",
    "settings.emailSuccess": "Cập nhật email thành công!",
    "settings.passwordSuccess": "Cập nhật mật khẩu thành công!",
    "settings.receiveSystem": "Nhận thông báo hệ thống",
    "settings.receiveAcademic": "Nhận thông báo học tập (điểm số)",
    "settings.receiveGoal": "Nhận thông báo mục tiêu (GPA)",
    "settings.receiveGpaMilestone": "Nhận thông báo cột mốc GPA",
    "notifications.title": "Thông Báo",
    "notifications.empty": "Không có thông báo nào",
    "notifications.markAllRead": "Đánh dấu tất cả đã đọc",
    "notifications.unreadOnly": "Chỉ xem chưa đọc",
    "notifications.system": "Hệ thống",
    "notifications.academic": "Học tập",
    "notifications.goal": "Mục tiêu",
    "notifications.gpaMilestone": "Cột mốc GPA",
    "admin.nav.dashboard": "Bảng điều khiển",
    "admin.nav.students": "Quản lý sinh viên",
    "admin.nav.notifications": "Thông báo Admin",
    "admin.nav.logs": "Lịch sử hoạt động",
    "admin.stats.totalStudents": "Tổng sinh viên",
    "admin.stats.activeStudents": "Sinh viên kích hoạt",
    "admin.stats.lockedAccounts": "Tài khoản bị khóa",
    "admin.stats.sysAverageGpa10": "GPA hệ 10 hệ thống",
    "admin.stats.sysAverageGpa4": "GPA hệ 4 hệ thống",
    "admin.stats.creditsCompleted": "Tín chỉ hoàn thành",
    "admin.stats.gpaDistribution": "Phân phối điểm GPA hệ 10",
    "admin.logs.title": "Lịch sử hoạt động hệ thống",
    "admin.notifications.title": "Gửi & Quản lý thông báo",
    "admin.notifications.history": "Lịch sử gửi thông báo",
    "admin.students.title": "Danh sách sinh viên",
    "admin.students.search": "Tìm kiếm sinh viên...",
    "admin.students.status": "Trạng thái tài khoản",
    "admin.students.lock": "Khóa tài khoản",
    "admin.students.unlock": "Mở khóa",
    "admin.students.resetPassword": "Đặt lại mật khẩu",
    "admin.students.details": "Chi tiết học tập",
    "admin.students.edit": "Chỉnh sửa thông tin",
    "admin.students.delete": "Xóa tài khoản"
  },
  en: {
    "login.title": "Sign In",
    "login.email": "Email Address",
    "login.password": "Password",
    "login.submit": "Sign In",
    "login.forgot": "Forgot password?",
    "login.registerLink": "Don't have an account? Register",
    "login.google": "Sign In with Google",
    "register.title": "Create Account",
    "register.firstName": "First Name",
    "register.lastName": "Last Name",
    "register.submit": "Create Account",
    "register.loginLink": "Already have an account? Sign In",
    "forgot.title": "Recover Password",
    "forgot.submit": "Send recovery link",
    "forgot.back": "Back to Sign In",
    "logout": "Logout",
    "dashboard": "Dashboard",
    "student": "Student",
    "admin": "Admin",
    "common.required": "This field is required.",
    "profile.title": "Student Profile",
    "profile.subtitle": "Manage your academic information, account details, and interface preferences",
    "profile.academicInfo": "Academic Information",
    "profile.personalInfo": "Personal Information",
    "profile.preferences": "Visual Preferences",
    "profile.changePassword": "Change Password",
    "profile.studentCode": "Student Code",
    "profile.university": "University Name",
    "profile.major": "Major Name",
    "profile.enrollmentYear": "Enrollment Year",
    "profile.requiredCredits": "Total Required Credits",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.email": "Email Address",
    "profile.save": "Save Changes",
    "profile.avatarUpload": "Change Avatar",
    "profile.currentPassword": "Current Password",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm New Password",
    "profile.passwordMismatch": "New passwords do not match.",
    "profile.success": "Profile updated successfully!",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "lang.vi": "Vietnamese",
    "lang.en": "English",
    "nav.academicYears": "Academic Years",
    "nav.statistics": "Statistics",
    "nav.goalPlanner": "Goal Planner",
    "nav.aiAdvisor": "AI Academic Advisor",
    "aiAdvisor.errLoadInsights": "Failed to load academic insights.",
    "aiAdvisor.errLoadMessages": "Failed to load chat history.",
    "aiAdvisor.threadLimitExceeded": "Maximum limit of 50 conversations reached.",
    "aiAdvisor.errStartThread": "Failed to start conversation.",
    "aiAdvisor.deleteConfirm": "Are you sure you want to delete this conversation?",
    "aiAdvisor.errDeleteThread": "Failed to delete conversation.",
    "aiAdvisor.errSendMessage": "Failed to send message.",
    "aiAdvisor.noConversations": "No conversations",
    "aiAdvisor.startChat": "Start advisor chat",
    "academicyears.title": "Academic Year Management",
    "academicyears.subtitle": "Create, update, or toggle your current active academic year",
    "academicyears.yearName": "Year Name",
    "academicyears.startYear": "Start Year",
    "academicyears.endYear": "End Year",
    "academicyears.status": "Status",
    "academicyears.current": "Current",
    "academicyears.completed": "Completed",
    "academicyears.actions": "Actions",
    "academicyears.addNew": "Add Academic Year",
    "academicyears.edit": "Edit Academic Year",
    "academicyears.delete": "Delete",
    "academicyears.deleteConfirm": "Are you sure you want to delete this academic year? All nested academic records will also be deleted.",
    "academicyears.save": "Save",
    "academicyears.cancel": "Cancel",
    "academicyears.makeCurrent": "Set as Current",
    "academicyears.success.create": "Academic year created successfully!",
    "academicyears.success.update": "Academic year updated successfully!",
    "academicyears.success.setCurrent": "Set current academic year successfully!",
    "semesters.title": "Semester Management",
    "semesters.subtitle": "Manage semesters within the academic year",
    "semesters.semesterName": "Semester Name",
    "semesters.addNew": "Add Semester",
    "semesters.edit": "Edit Semester",
    "semesters.delete": "Delete",
    "semesters.deleteConfirm": "Are you sure you want to delete this semester? All nested academic records will also be deleted.",
    "semesters.save": "Save",
    "semesters.cancel": "Cancel",
    "semesters.empty": "No semesters yet",
    "semesters.backToYears": "Back to Academic Years",
    "semesters.success.create": "Semester created successfully!",
    "semesters.success.update": "Semester updated successfully!",
    "semesters.success.delete": "Semester deleted successfully!",
    "courses.title": "Course Management",
    "courses.subtitle": "Manage your academic courses, credits, and details",
    "courses.courseCode": "Course Code",
    "courses.courseName": "Course Name",
    "courses.credits": "Credits",
    "courses.isRetake": "Retake Course",
    "courses.originalCourse": "Original Attempt Course",
    "courses.status": "Status",
    "courses.status.inProgress": "In Progress",
    "courses.status.completed": "Completed",
    "courses.addNew": "Add Course",
    "courses.edit": "Edit Course",
    "courses.delete": "Delete",
    "courses.deleteConfirm": "Are you sure you want to delete this course?",
    "courses.save": "Save",
    "courses.cancel": "Cancel",
    "courses.empty": "No courses yet",
    "courses.backToSemesters": "Back to Semesters",
    "courses.searchPlaceholder": "Search by name or code...",
    "courses.totalCredits": "Total Credits",
    "courses.success.create": "Course added successfully!",
    "courses.success.update": "Course updated successfully!",
    "courses.success.delete": "Course deleted successfully!",
    "scores.title": "Grade Management",
    "scores.attendance": "Attendance Score",
    "scores.continuous": "Continuous Assessment Score",
    "scores.final": "Final Exam Score",
    "scores.courseScore": "Course Score",
    "scores.letterGrade": "Letter Grade",
    "scores.gpa4": "GPA 4.0 Score",
    "scores.classification": "Academic Classification",
    "scores.status": "Status",
    "scores.pass": "Pass",
    "scores.fail": "Fail",
    "scores.editTitle": "Input Component Scores",
    "scores.save": "Save Scores",
    "scores.auditLogs": "Score Change Logs",
    "scores.field": "Component Modified",
    "scores.oldVal": "Old Value",
    "scores.newVal": "New Value",
    "scores.changedAt": "Modified At",
    "scores.success.update": "Scores updated successfully!",
    "scores.clear": "Clear Scores",
    "scores.clearConfirm": "Are you sure you want to clear the scores for this course? All component scores will be reset.",
    "gpa.title": "Academic GPA & Results",
    "gpa.subtitle": "Track and analyze your cumulative progress, average GPAs, and academic classification",
    "gpa.cumulative": "Cumulative GPA",
    "gpa.semester": "Semester GPA",
    "gpa.year": "Academic Year GPA",
    "gpa.credits.completed": "Completed Credits",
    "gpa.credits.required": "Required Credits",
    "gpa.progress": "Completion Progress",
    "gpa.classification": "Academic Classification",
    "gpa.academicClassification": "Classification",
    "gpa.passedCredits": "Passed Credits",
    "gpa.failedCredits": "Failed Credits",
    "gpa.credits": "Credits",
    "gpa.average10": "Average GPA (10-scale)",
    "gpa.average4": "Average GPA (4-scale)",
    "gpa.semesterSelect": "Select a semester to view details",
    "gpa.yearSelect": "Select Academic Year",
    "gpa.empty": "No academic results recorded yet. Please input course scores to calculate your GPA.",
    "nav.settings": "Settings",
    "settings.title": "System Settings",
    "settings.subtitle": "Manage visual preferences, notification types, and account security",
    "settings.preferences": "Visual Preferences",
    "settings.notifications": "Notification Toggles",
    "settings.account": "Account Settings",
    "settings.email": "Email Address",
    "settings.changeEmail": "Update Email",
    "settings.changePassword": "Change Password",
    "settings.save": "Save Preferences",
    "settings.success": "Settings updated successfully!",
    "settings.emailSuccess": "Email updated successfully!",
    "settings.passwordSuccess": "Password changed successfully!",
    "settings.receiveSystem": "Receive System Notifications",
    "settings.receiveAcademic": "Receive Academic Notifications (Grades)",
    "settings.receiveGoal": "Receive Goal Notifications (Target GPA)",
    "settings.receiveGpaMilestone": "Receive GPA Milestone Notifications",
    "notifications.title": "Notifications",
    "notifications.empty": "No notifications",
    "notifications.markAllRead": "Mark all as read",
    "notifications.unreadOnly": "Unread only",
    "notifications.system": "System",
    "notifications.academic": "Academic",
    "notifications.goal": "Goal",
    "notifications.gpaMilestone": "GPA Milestone",
    "admin.nav.dashboard": "Admin Dashboard",
    "admin.nav.students": "Student Management",
    "admin.nav.notifications": "Notifications Center",
    "admin.nav.logs": "Activity Log Audit",
    "admin.stats.totalStudents": "Total Students",
    "admin.stats.activeStudents": "Active Students",
    "admin.stats.lockedAccounts": "Locked Accounts",
    "admin.stats.sysAverageGpa10": "Sys Avg GPA (10-scale)",
    "admin.stats.sysAverageGpa4": "Sys Avg GPA (4-scale)",
    "admin.stats.creditsCompleted": "Total System Credits",
    "admin.stats.gpaDistribution": "GPA Distribution (10-scale)",
    "admin.logs.title": "System Activity Audit Log",
    "admin.notifications.title": "Admin Notification Center",
    "admin.notifications.history": "Notification Dispatch History",
    "admin.students.title": "Student Enrollment Registry",
    "admin.students.search": "Search students...",
    "admin.students.status": "Account Status",
    "admin.students.lock": "Lock Account",
    "admin.students.unlock": "Unlock Account",
    "admin.students.resetPassword": "Reset Password",
    "admin.students.details": "Academic Records",
    "admin.students.edit": "Edit Profile Details",
    "admin.students.delete": "Soft Delete Account"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'vi' || saved === 'en') return saved;
    return 'vi';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const dict = translations[language];
    return (dict as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
