USE [master];
GO
ALTER DATABASE [AcademicGPA] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
RESTORE DATABASE [AcademicGPA]
FROM DISK = N'/var/opt/mssql/backup/AcademicGPA.bak'
WITH FILE = 1, REPLACE, NOUNLOAD, STATS = 10;
GO
ALTER DATABASE [AcademicGPA] SET MULTI_USER;
GO
